// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package menu.domain;

import menu.domain.Ingredient;

privileged aspect Ingredient_Roo_JavaBean {
    
    public String Ingredient.getMylabel() {
        return this.Mylabel;
    }
    
    public void Ingredient.setMylabel(String Mylabel) {
        this.Mylabel = Mylabel;
    }
    
}
