// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package menu.domain;

import menu.domain.Realisation;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Realisation_Roo_Configurable {
    
    declare @type: Realisation: @Configurable;
    
}
